# Generated by Django 5.0.6 on 2024-05-31 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img_address',
            field=models.URLField(default='https://1000logos.net/wp-content/uploads/2020/02/The-Doors-Logo.jpg'),
        ),
    ]
