# Generated by Django 5.0.6 on 2024-06-06 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='author_id',
        ),
    ]
